### ISSUE TITLE
Encrypted rar file

### ISSUE THREAD

**Issue by gjermshus** [julianperrott/SimCityBuildItBot#5]
Any possibility to decrypt (remove password) from the rar file with item images. Would love to build on your work to evolve a SC bit!

**Comment by julianperrott** [comment]
Hi, I can’t remember how the bot runs, I assume you click the “Start Crafting” button. I don’t have memu installed anymore and I haven’t played the sim city game for a few years so I can’t run it myself. I am sure that there are some good tutorials on the web for creating Pixel bots. The images are probably out of date by now. Password: “Images.rar”
